var isDone = true;
var decVar = 23;
var myname = "Rajat Goel";
var fullname = " Hey, I'm  " + myname + " . \nand i'm " + (decVar + 2);
var arr = [1, 2, 3, 4];
var newarr = [1, 2, 3, 4];
console.log("isDone", isDone);
console.log("decVar", decVar);
console.log("myname", myname, "and fullName is \n\n", fullname);
console.log("arr", arr, "\n\n newarr", newarr);
